// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"geek.xingx/egPractice/internal/server/repo"
	"geek.xingx/egPractice/internal/server/service"
	"geek.xingx/egPractice/internal/server/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitArticleService() (*service.ArticleService, error) {
	iArticleRepo := repo.NewArticleRepository()
	iArticleUseCase := usecase.NewArticleUseCase(iArticleRepo)
	articleService := service.NewArticleService(iArticleUseCase)
	return articleService, nil
}

// wire.go:

var (
	articleSet = wire.NewSet(usecase.NewArticleUseCase, repo.NewArticleRepository, service.NewArticleService)
)
